/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omar_retromp3recorder_app_recorder_LameModule */

#ifndef _Included_com_omar_retromp3recorder_app_recorder_LameModule
#define _Included_com_omar_retromp3recorder_app_recorder_LameModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omar_retromp3recorder_app_recorder_LameModule
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_omar_retromp3recorder_app_recorder_LameModule_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_omar_retromp3recorder_app_recorder_LameModule
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_omar_retromp3recorder_app_recorder_LameModule_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_omar_retromp3recorder_app_recorder_LameModule
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_omar_retromp3recorder_app_recorder_LameModule_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_omar_retromp3recorder_app_recorder_LameModule
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omar_retromp3recorder_app_recorder_LameModule_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
